config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get('/about', { to: 'about#index'} )

  get('/contact', {to: 'contact#index'})

  post('/contact', {to: 'contact#create', as: 'contact_submit'})

  # get('/products/new', { to: 'products#new', as: 'new_product' })
  # post('/products', { to: 'products#create', as: 'products' })
  #
  # get('/products/:id', { to: 'products#show', as: 'product' })
  #
  #
  # get('/products', { to: 'products#index' })
  #
  # get('/products/:id/edit', { to: 'products#edit', as: 'edit_product' })
  #
  # patch('/products/:id', { to: 'products#update' })
  #
  # delete('/products/:id', { to: 'products#destroy' })

  resources :products do
    resources :reviews
  end

  root 'welcome#index'
 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  
  has_many :reviews, dependent: :destroy

   validates(:title, { presence: { message: 'must be present!' },
                     uniqueness: { case_sensitive: false } })
  validates(:Description,{ presence: true, length: { minimum: 10 } })
  validates(:price, { presence: true,
                         numericality: { greater_than_or_equal_to: 0 }})

   def self.search(str)
    where('title ILIKE? OR "Description" ILIKE ?',"%#{str}%", "%#{str}%").order("title")
    #  SELECT FROM products WHERE title or Description = str
  end
 #   A callback method to set the default price to 1
 # A callback method to capitalize the product title before saving
before_save :capitalize_title



private

def capitalize_title
    self.title = title.capitalize if title.present?
  end

 def set_defualt
     self.price ||= 1
 end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product

  validates :rating, presence: true, inclusion: {in: 1..5 }
end

app/models/user.rb
class User < ApplicationRecord
  def self.search(str)
   where('first_name ILIKE? OR last_name ILIKE?  OR email ILIKE? ',"%#{str}%", "%#{str}%", "%#{str}%")
  #  SELECT FROM products WHERE title or Description = str
 end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index

  end

  def create
    #  render plain: "Thank you #{params[:name]} for contacting us"
     redirect_to contact_path({name: params[:name]})

  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def new
   @product = Product.new
  end

  def create
    # the line below is what's called "Strong Parameters" feautre that was added
    # to Rails starting with version 4 to help developer be more explicit about
    # the parameters that they want to allow the user to submit
    product_params = params.require(:product).permit([:title, :Description, :price,:category_id, :rating])
    @product = Product.new product_params
    if @product.save
      # redirect_to question_path({id: @question.id})
      # redirect_to question_path(@question.id)
      redirect_to product_path(@product)
    else
      # render 'questions/new'
      render :new
    end
  end

  def show
    @product = Product.find params[:id]
    @review = Review.new
  end

  def index
    @products = Product.order(created_at: :desc).limit(20)
  end

  def edit
    @product = Product.find params[:id]
  end

  def update
    @product = Product.find params[:id]
    product_params = params.require(:product).permit([:title, :body, :category_id, :rating])
    if @product.update(product_params)
      redirect_to product_path(@product)
    else
      render :edit
    end
  end

  def destroy
    product = Product.find params[:id]
    product.destroy
    redirect_to products_path
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index

  end
  def create
    @product = Product.find(params[:product_id])
    review_params = params.require(:review).permit(:body, :rating)
    @review = Review.new(review_params)
    @review.product = @product

    # @answer = @question.answers.build(answer_params)

    if @review.save
      redirect_to product_path(@product), notice: 'Review Created!'
    else
      render '/products/show'
    end
  end

  def destroy
    review = Review.find(params[:id])
    review.destroy
    redirect_to product_path(review.product), notice: 'Review deleted!'
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/about/index.html.erb
<h1>About Page</h1>

app/views/contact/index.html.erb
<h1>Contact Page</h1>

<% if params[:name].present? %>
Hi, <%= params[:name] %>,Thank you for contacting us, We will contact you soon!!
<% end %><br><br>
<hr><br>

<%= form_tag contact_submit_path do %>
  <div>
    <%= label_tag :name %>
    <%= text_field_tag :name %>
  </div>
  <div>
    <%= label_tag :email %>
    <%= email_field_tag :email %>
  </div>
  <div>
    <%= label_tag :message %>
    <%= text_area_tag :message %>
  </div><br>
  <%# will generates a submit button for the form with label 'Contact Us' %>
  <%= submit_tag 'Contact Us' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Amazon</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">HOME</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "PRODUCTS" , products_path %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Create New Product" , new_product_path %></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/products/edit.html.erb
<br>
<div class="well">
<h1>Edit Product</h1>
</div>

<%= @product.errors.full_messages.join(', ') %>
<%= form_for @product do |f| %>
<% if @product.errors.any? %>
    <% @product.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
    <% end %>
<div>
  <%= f.label :title%>
  <%= f.text_field(:title, {:class => 'form-control'}) %>
</div>
<div>
  <%= f.label :Description%>
  <%= f.text_area(:Description, {:class => 'form-control'}) %>
</div>
<div>
  <%= f.label :price%>
  <%= f.text_area(:price, {:class => 'form-control'}) %>
</div><br><br>
<%= f.submit({:class => 'btn btn-primary'}) %>
<% end %>

app/views/products/index.html.erb
<br>
<div class="well">
<h1>All Products</h1>
</div>
<br><hr><br>
<% @products.each do |product| %>
<div class="well">
  <h1><%= product.title %></h1>
  <h4><%= product.Description %></h4>
  <h4><%= product.price %></h4>

  <p><%= link_to "Read More", product_path(product), :class => 'btn btn-default' %></p>
</div>
<% end %>

app/views/products/new.html.erb
<br>
<div class="well">
  <h1>New Product</h1>
</div>
<hr>
<%= form_for @product do |f| %>
  <% if @product.errors.any? %>
    <% @product.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>
  <div>
    <%= f.label :title %>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
  </div>
  <div>
    <%= f.label :Description %>
    <%= f.text_area(:Description, {:class => 'form-control'}) %>
  </div>
  <div>
    <%= f.label :price %>
    <%= f.text_field(:price, {:class => 'form-control'}) %>
  </div><br>
  <p>
    <div class="">
      <%= f.collection_select :category_id, Category.all, :id, :name %>
    </div><br>
  <%= f.submit('Submit',{:class => 'btn btn-primary'}) %>
  </p>
<% end %>

app/views/products/show.html.erb
<br>
<div class="well">
<h1><%= @product.title %></h1>
<h3><%= @product.Description %></h3>
<p><%= @product.price %></p>
</div>



<%= link_to 'Edit', edit_product_path(@product), :class => 'btn btn-default' %>

<%# Rails enables us to make links end non-GET requests by setting the `method`
    attribute for `link_to`. Rails uses Javascript to accomplish that. %>
<%= link_to 'Delete', product_path(@product),
                      method: :delete,
                      data: { confirm: 'Are you sure?' },
                      :class => 'btn btn-danger'%>

<%= link_to 'Save', products_path, :class => 'btn btn-success' %>

<hr>

<h2>Add a Review</h2>
<%= form_for [@product, @review] do |f| %>
  <div>

    <%= f.label :body %>
    <%= f.text_area(:body, {:class => 'form-control'}) %><br>

    <%= f.label :rating %>
    <%= f.text_field(:rating, {:class => 'form-control'}) %>

  </div><br>

  <%= f.submit({:class => 'btn btn-default'}) %>
<% end %>
<hr>


<%  @product.reviews.each do |review| %>
<div class="well">
  <h4>Title : <%= review.body %></h4>
  <p>Review : <%= review.rating %></p>
  <hr>
  <%= link_to(
  'Delete', product_review_path(@product, review), method: :delete,
  data:{confirm: 'Are you sure!!'}, :class => 'btn btn-danger')%>
  <hr />
</div>
  <% end %>

app/views/reviews/index.html.erb
<%  @products.each do |review| %>
   <%= review.body %>
   <%= review.rating %>
   <% end %>

app/views/welcome/index.html.erb
<div class="jumbotron text-center">
<h1>Welcome Page</h1><br><br>
</div>